apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-code
data:
  server.js: |
    const express = require('express');
    const app = express();
    const port = 3000;

    app.get('/products', (req, res) => {
      res.json([
        { id: 1, name: 'Phone' },
        { id: 2, name: 'Laptop' }
      ]);
    });

    app.listen(port, () => {
      console.log(`Product service running on port ${port}`);
    });

  package.json: |
    {
      "name": "product-service",
      "version": "1.0.0",
      "main": "server.js",
      "scripts": {
        "start": "node server.js"
      },
      "dependencies": {
        "express": "^4.18.2"
      }
    }
